run_name: "Run2_Amz_dropout"
data: "amz"

train_contrastive: True
train_head: True

self_supervised:
  augmentations: "dropout"
  percentage_masking_features: 0.15
  percentage_masking_edges: 0.15

batch_size: 15000
epochs: 500
early_stopping: 50
lr: 0.01
weight_decay: 0.0001

triplets:
  mining_margin: 1
  loss_margin: 1

model_name: "GCN_Att_Not_res"
model:
  dropout: 0.3
  hidden_channels: 40
  out_channels: 30
  num_layers: 1
  in_channels: 25

squeduler:
  type: "StepLR"
  step_size: 50
  gamma: 0.7


