run_name: "Run15_Yelp"
data: "yelp"

# Per propagar alhora la loss del triplet i la crossentropy
ContrastiveAndClassification: True
weight_triplet: 1
weight_classification: 1

OnlyEval: False

batch_size: 500
epochs: 100
early_stopping: 30
lr: 0.001
weight_decay: 0.0001

triplets:
  mining_margin: 1
  loss_margin: 1

model_name: "GIN_ReLU"
model:
  dropout_GIN: 0.05
  dropout: 0.3
  hidden_channels: 40
  out_channels: 35
  num_layers: 2
  in_channels: 32


squeduler:
  type: "StepLR"
  step_size: 25
  gamma: 0.65