run_name: "Run20_Yelp"
data: "yelp"

# Per propagar alhora la loss del triplet i la crossentropy
ContrastiveAndClassification: True
weight_triplet: 1
weight_classification: 1

OnlyEval: False

# If not set uses tsne
DimReduction: "autoencoder"


batch_size: 500
epochs: 200
early_stopping: 40
lr: 0.001
weight_decay: 0.0001

triplets:
  mining_margin: 1
  loss_margin: 1

model_name: "GraphSAGE_model"
model:
  dropout_SAGE: 0.15
  dropout: 0.3
  hidden_channels: 40
  out_channels: 35
  num_layers: 2
  in_channels: 32


squeduler:
  type: "StepLR"
  step_size: 25
  gamma: 0.65