run_name: "Run23_Yelp"
data: "yelp"

train_contrastive: True
train_head: True

batch_size: 150
epochs: 100
early_stopping: 30
lr: 0.001
weight_decay: 0.0001

triplets:
  mining_margin: 1
  loss_margin: 1

model_name: "PNA_model"
model:
  dropout_PNA: 0.15
  dropout: 0.3
  hidden_channels: 40
  out_channels: 35
  num_layers: 3
  in_channels: 32

squeduler:
  type: "StepLR"
  step_size: 25
  gamma: 0.65